name: CI

on:
  # allows us to run workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

env:
  OMP_NUM_THREADS: 2
  QT_QPA_PLATFORM: offscreen

jobs:
  ci:
    runs-on: ubuntu-latest
    container: openmc/openmc:develop
    steps:
      -
        name: Apt dependencies
        shell: bash
        run: |
          apt update
          apt install -y libglu1-mesa libglib2.0-0 libfontconfig1 libegl-dev
      -
        uses: actions/checkout@v2
      -
        name: Install
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}
          pip install .[test]
      -
        name: Test
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}
          pytest -v tests
