name: CI

on:
  # allows us to run workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

env:
  OMP_NUM_THREADS: 2
  QT_QPA_PLATFORM: offscreen

jobs:
  ci:
    runs-on: ubuntu-latest
    container: openmc/openmc:develop
    env:
      DISPLAY: ':99.0'
    steps:
      -
        name: Apt dependencies
        shell: bash
        run: |
          apt update
          apt install -y libglu1-mesa libglib2.0-0 libfontconfig1 libegl-dev libxkbcommon-x11-0 xvfb libdbus-1-3
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
      -
        uses: actions/checkout@v2
      -
        name: Install
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}
          pip install .[test]
      -
        name: Test
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}
          pytest -v tests
